import { ProjectManifest } from './types';

export const DEFAULT_PROJECT_MANIFEST: Readonly<ProjectManifest> = {
  schemaVersion: 1,
  projectId: 'default-avatar',
  metadata: {
    name: 'Sample Avatar (Chibi Cat)',
    createdAt: '2026-09-05T01:30:00.000Z',
    updatedAt: '2026-09-05T01:30:00.000Z',
    version: '1.0.0',
  },
  canvas: {
    width: 1920,
    height: 1080,
    fps: 60,
  },
  assets: [
    {
      id: 'asset-body',
      name: 'Body',
      path: 'sample_avatar/assets/body.png',
      format: 'png',
    },
    {
      id: 'asset-eye-open',
      name: 'Eye Open',
      path: 'sample_avatar/assets/eye-open.png',
      format: 'png',
    },
    {
      id: 'asset-eye-closed',
      name: 'Eye Closed',
      path: 'sample_avatar/assets/eye-closed.png',
      format: 'png',
    },
    {
      id: 'asset-mouth-closed',
      name: 'Mouth Closed',
      path: 'sample_avatar/assets/mouth-closed.png',
      format: 'png',
    },
    {
      id: 'asset-mouth-small',
      name: 'Mouth Small',
      path: 'sample_avatar/assets/mouth-small.png',
      format: 'png',
    },
    {
      id: 'asset-mouth-open',
      name: 'Mouth Open',
      path: 'sample_avatar/assets/mouth-open.png',
      format: 'png',
    },
    {
      id: 'asset-mouth-wide',
      name: 'Mouth Wide',
      path: 'sample_avatar/assets/mouth-wide.png',
      format: 'png',
    },
  ],
  layers: [
    {
      id: 'layer-body',
      name: 'Body',
      type: 'sprite',
      assetId: 'asset-body',
      role: 'body',
      x: 960,
      y: 540,
      scaleX: 1.4,
      scaleY: 1.4,
      rotation: 0,
      opacity: 1.0,
      visible: true,
      zIndex: 1,
    },
    {
      id: 'layer-eye-open',
      name: 'Eye Open',
      type: 'sprite',
      assetId: 'asset-eye-open',
      role: 'eye_open',
      x: 960,
      y: 540,
      scaleX: 1.4,
      scaleY: 1.4,
      rotation: 0,
      opacity: 1.0,
      visible: true,
      zIndex: 10,
    },
    {
      id: 'layer-eye-closed',
      name: 'Eye Closed',
      type: 'sprite',
      assetId: 'asset-eye-closed',
      role: 'eye_closed',
      x: 960,
      y: 540,
      scaleX: 1.4,
      scaleY: 1.4,
      rotation: 0,
      opacity: 1.0,
      visible: true,
      zIndex: 11,
    },
    {
      id: 'layer-mouth-closed',
      name: 'Mouth Closed',
      type: 'sprite',
      assetId: 'asset-mouth-closed',
      role: 'mouth_closed',
      x: 960,
      y: 540,
      scaleX: 1.4,
      scaleY: 1.4,
      rotation: 0,
      opacity: 1.0,
      visible: true,
      zIndex: 20,
    },
    {
      id: 'layer-mouth-small',
      name: 'Mouth Small',
      type: 'sprite',
      assetId: 'asset-mouth-small',
      role: 'mouth_small',
      x: 960,
      y: 540,
      scaleX: 1.4,
      scaleY: 1.4,
      rotation: 0,
      opacity: 1.0,
      visible: true,
      zIndex: 21,
    },
    {
      id: 'layer-mouth-open',
      name: 'Mouth Medium',
      type: 'sprite',
      assetId: 'asset-mouth-open',
      role: 'mouth_medium',
      x: 960,
      y: 540,
      scaleX: 1.4,
      scaleY: 1.4,
      rotation: 0,
      opacity: 1.0,
      visible: true,
      zIndex: 22,
    },
    {
      id: 'layer-mouth-wide',
      name: 'Mouth Wide',
      type: 'sprite',
      assetId: 'asset-mouth-wide',
      role: 'mouth_wide',
      x: 960,
      y: 540,
      scaleX: 1.4,
      scaleY: 1.4,
      rotation: 0,
      opacity: 1.0,
      visible: true,
      zIndex: 23,
    },
  ],
  idleConfig: {
    enabled: true,
    amplitude: 8,
    speed: 1.5,
  },
  blinkConfig: {
    enabled: true,
    minIntervalMs: 3000,
    maxIntervalMs: 6000,
    durationMs: 150,
  },
  expressionConfig: {
    activeExpression: 'neutral',
    expressions: [
      {
        id: 'neutral',
        name: 'Neutral',
        layerOverrides: {},
      },
      {
        id: 'happy',
        name: 'Happy',
        layerOverrides: {
          'layer-eye-open': { scaleX: 1.05, scaleY: 1.05 },
        },
      },
      {
        id: 'angry',
        name: 'Angry',
        layerOverrides: {
          'layer-eye-open': { rotation: -3 },
        },
      },
      {
        id: 'sad',
        name: 'Sad',
        layerOverrides: {
          'layer-eye-open': { y: 546 },
        },
      },
      {
        id: 'shock',
        name: 'Shock',
        layerOverrides: {
          'layer-eye-open': { scaleX: 1.2, scaleY: 1.2 },
        },
      },
      {
        id: 'embarrassed',
        name: 'Embarrassed',
        layerOverrides: {
          'layer-body': { opacity: 0.92 },
        },
      },
    ],
    hotkeys: [
      { expressionId: 'neutral', key: 'F1' },
      { expressionId: 'happy', key: 'F2' },
      { expressionId: 'angry', key: 'F3' },
      { expressionId: 'sad', key: 'F4' },
    ],
  },
  mouthConfig: {
    thresholds: {
      closed: 0.15,
      small: 0.35,
      medium: 0.65,
    },
    continuousMode: false,
  },
  audioConfig: {
    threshold: 0.15,
    sensitivity: 2.0,
    releaseDelayMs: 150,
  },
  outputConfig: {
    preferredPort: 17777,
    transparent: true,
  },
};

export const DEFAULT_EXPRESSIONS = DEFAULT_PROJECT_MANIFEST.expressionConfig!.expressions;
export const DEFAULT_HOTKEYS = DEFAULT_PROJECT_MANIFEST.expressionConfig!.hotkeys!;
export const DEFAULT_MOUTH_THRESHOLDS = DEFAULT_PROJECT_MANIFEST.mouthConfig!.thresholds;
export const DEFAULT_MOUTH_CONFIG = DEFAULT_PROJECT_MANIFEST.mouthConfig!;
